// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sunhvkbaulchnuojgirj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1bmh2a2JhdWxjaG51b2pnaXJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MjEzNzksImV4cCI6MjA2NzE5NzM3OX0.UgIIP1qsimRtgyU7M4yrqaNsZXw7FjukSHz86WRRp80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});